import json
import re
from pathlib import Path

from bs4 import BeautifulSoup, Tag
from langchain_text_splitters import RecursiveCharacterTextSplitter


DATA_DIR = Path("data/sec")

CHUNK_SIZE = 1200
CHUNK_OVERLAP = 200


def load_metadata(html_path: Path) -> dict:
    """Load metadata generated by ingest.py."""

    metadata_path = html_path.with_suffix(".json")

    if not metadata_path.exists():
        raise FileNotFoundError(
            f"Metadata file not found: {metadata_path}"
        )

    metadata = json.loads(
        metadata_path.read_text(encoding="utf-8")
    )

    return metadata


def clean_html(html_path: Path) -> BeautifulSoup:
    """
    Remove HTML/XBRL noise while keeping the actual
    filing content.
    """

    html = html_path.read_text(
        encoding="utf-8",
        errors="ignore",
    )

    soup = BeautifulSoup(html, "html.parser")

    # Remove XBRL header.
    for tag in soup.find_all():
        if tag.name and tag.name.lower() == "ix:header":
            tag.decompose()

    # Remove hidden elements.
    for tag in soup.find_all(style=True):
        style = tag.get("style", "").lower()

        if "display:none" in style.replace(" ", ""):
            tag.decompose()

    # Remove things that are not document content.
    for tag in soup.find_all(
        ["script", "style", "noscript", "svg"]
    ):
        tag.decompose()

    return soup


def normalize_text(text: str) -> str:
    """Normalize whitespace."""

    text = re.sub(r"\s+", " ", text)

    return text.strip()


def table_to_text(table: Tag) -> str:
    """
    Convert an HTML table into readable text while
    keeping the table together.
    """

    rows = []

    for row in table.find_all("tr"):

        cells = []

        for cell in row.find_all(["th", "td"]):

            value = normalize_text(
                cell.get_text(" ", strip=True)
            )

            if value:
                cells.append(value)

        if cells:
            rows.append(" | ".join(cells))

    if not rows:
        return ""

    return "[TABLE]\n" + "\n".join(rows) + "\n[/TABLE]"


def is_heading(tag: Tag) -> bool:
    """
    Generic heading detection.

    We prefer actual HTML heading tags and use a few
    generic structural signals as fallback.
    """

    if tag.name in {
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
    }:
        return True

    if tag.name not in {
        "div",
        "p",
        "span",
    }:
        return False

    text = normalize_text(
        tag.get_text(" ", strip=True)
    )

    if not text or len(text) > 200:
        return False

    # SEC "Item X" headings are a useful generic
    # structural signal across filings.
    if re.match(
        r"^Item\s+\d+[A-Z]?\b",
        text,
        flags=re.IGNORECASE,
    ):
        return True

    # Generic HTML formatting signals.
    style = tag.get("style", "").lower()

    if "font-weight:bold" in style.replace(" ", ""):
        return True

    if "font-weight:700" in style.replace(" ", ""):
        return True

    # <b> / <strong> used as standalone short text.
    if tag.name in {"b", "strong"}:
        return True

    return False


def extract_blocks(soup: BeautifulSoup) -> list[dict]:
    """
    Convert the cleaned HTML into logical document blocks.

    Blocks are:

        heading
        paragraph
        table
    """

    blocks = []

    body = soup.body or soup

    for element in body.find_all(
        ["h1", "h2", "h3", "h4", "h5", "h6",
         "div", "p", "table"],
        recursive=True,
    ):

        # ---------------------------------------------
        # Tables
        # ---------------------------------------------

        if element.name == "table":

            text = table_to_text(element)

            if text:
                blocks.append(
                    {
                        "type": "table",
                        "text": text,
                    }
                )

            continue

        # ---------------------------------------------
        # Headings
        # ---------------------------------------------

        if is_heading(element):

            text = normalize_text(
                element.get_text(
                    " ",
                    strip=True,
                )
            )

            if text:
                blocks.append(
                    {
                        "type": "heading",
                        "text": text,
                    }
                )

            continue

        # ---------------------------------------------
        # Paragraphs / text
        # ---------------------------------------------

        if element.name in {
            "div",
            "p",
        }:

            text = normalize_text(
                element.get_text(
                    " ",
                    strip=True,
                )
            )

            if text:
                blocks.append(
                    {
                        "type": "paragraph",
                        "text": text,
                    }
                )

    return blocks


def build_sections(blocks: list[dict]) -> list[dict]:
    """
    Group blocks under the most recently encountered
    heading.

    If heading detection misses something, the content
    still remains retrievable.
    """

    sections = []

    current_title = "Document"

    current_blocks = []

    for block in blocks:

        if block["type"] == "heading":

            if current_blocks:

                sections.append(
                    {
                        "title": current_title,
                        "blocks": current_blocks,
                    }
                )

            current_title = block["text"]

            current_blocks = []

        else:

            current_blocks.append(block)

    if current_blocks:

        sections.append(
            {
                "title": current_title,
                "blocks": current_blocks,
            }
        )

    return sections


def chunk_sections(
    sections: list[dict],
) -> list[dict]:
    """
    Chunk each logical section.

    RecursiveCharacterTextSplitter is used AFTER
    document structure has been extracted.

    Tables are kept together as much as possible.
    """

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=CHUNK_SIZE,
        chunk_overlap=CHUNK_OVERLAP,
        separators=[
            "\n\n",
            "\n",
            ". ",
            " ",
            "",
        ],
    )

    chunks = []

    chunk_index = 0

    for section in sections:

        section_title = section["title"]

        # Build text from the blocks belonging to this
        # section.
        section_parts = []

        for block in section["blocks"]:

            section_parts.append(
                block["text"]
            )

        section_text = "\n\n".join(
            section_parts
        ).strip()

        if not section_text:
            continue

        section_chunks = splitter.split_text(
            section_text
        )

        for text in section_chunks:

            chunks.append(
                {
                    "text": text,
                    "section": section_title,
                    "chunk_index": chunk_index,
                }
            )

            chunk_index += 1

    return chunks


def process_filing(html_path: Path) -> list[dict]:
    """Complete processing pipeline."""

    metadata = load_metadata(html_path)

    soup = clean_html(html_path)

    blocks = extract_blocks(soup)

    sections = build_sections(blocks)

    chunks = chunk_sections(sections)

    processed_chunks = []

    for chunk in chunks:

        processed_chunks.append(
            {
                "id": (
                    f"{metadata['ticker']}_"
                    f"{metadata['filing_date']}_"
                    f"{chunk['chunk_index']}"
                ),

                "text": chunk["text"],

                "metadata": {
                    "ticker": metadata["ticker"],
                    "company": metadata["company"],
                    "filing_type": metadata["filing_type"],
                    "filing_date": metadata["filing_date"],
                    "accession_number": metadata[
                        "accession_number"
                    ],
                    "source": "SEC",
                    "section": chunk["section"],
                    "chunk_index": chunk[
                        "chunk_index"
                    ],
                },
            }
        )

    return processed_chunks


if __name__ == "__main__":

    html_files = list(
        DATA_DIR.glob("*.html")
    )

    if not html_files:
        raise FileNotFoundError(
            "No HTML filings found in data/sec/"
        )

    # Test the first filing.
    html_path = html_files[0]

    print("=" * 60)
    print("PROCESSING")
    print("=" * 60)

    print(f"File: {html_path}")

    chunks = process_filing(html_path)

    print(
        f"\nNumber of chunks: {len(chunks)}"
    )

    print("\n" + "=" * 60)
    print("FIRST 5 CHUNKS")
    print("=" * 60)

    for chunk in chunks[:5]:

        print("\n" + "-" * 60)

        print(f"ID: {chunk['id']}")

        print("\nMetadata:")

        print(
            json.dumps(
                chunk["metadata"],
                indent=2,
            )
        )

        print("\nText:")

        print(chunk["text"][:1500])